version: '3'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8087:1920"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres_db
      SPRING_DATASOURCE_PASSWORD: password

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: houssemeddine.mars@esprit.tn
      PGADMIN_DEFAULT_PASSWORD: testtest123

volumes:
  postgres-data:
